// ============================================================
//  characters.js — 角色数据配置
//  想修改角色介绍、台词、属性，只需编辑这个文件
// ============================================================

const characters = [
  {
    slug: 'naruhodou',
    img: 'chars/naruhodou.png',
    facingRight: true,
    name: '成步堂',
    title: '律师 · 成步堂法律事务所',
    zone: 'office',           // 初始区域：office / kitchen / toilet
    quote: '"绝不是在虚张声势"',
    stats: {
      '职业': '辩护律师',
      '胜率': '100%',
      '口头禅': '异议！',
      '发型': '刺猬头',
    },
    phrases: [
      '我有异议！',
      '看这个！',
      '这里有矛盾！',
      '我绝对不会放弃！',
      '在这里逆转思维的话……',
    ],
  },
  {
    slug: 'mayoi',
    img: 'chars/mayoi.png',
    facingRight: false,
    name: '真宵',
    title: '灵媒见习生 · 神里家',
    zone: 'office',
    quote: '"还是个不成熟的灵媒"',
    stats: {
      '职业': '灵媒（见习）',
      '特技': '灵媒术',
      '最爱': '将军超人',
      '食量': '超大',
    },
    phrases: [
      '我饿了...',
      '成步堂哥，晚上去吃拉面吗？',
      '姐姐教过我！',
      '将军超人最帅了！',
      '这里的环境真不错啊',
    ],
  },
  {
    slug: 'chihiro',
    img: 'chars/chihiro.png',
    facingRight: false,
    name: '千寻',
    title: '首席律师',
    zone: 'office',
    quote: '"证据会说话。"',
    stats: {
      '职业': '首席律师',
      '经验': '丰富',
      '特长': '虚张声势',
      '气场': '强大',
    },
    phrases: [
      '尝试逆转思路吧！',
      '相信你的委托人。',
      '这个证据很关键。',
      '成步堂，不要慌张。',
      '真相终会大白！',
    ],
  },
  {
    slug: 'mitsurugi',
    img: 'chars/mitsurugi.png',
    facingRight: false,
    name: '御剑',
    title: '天才检察官 · 无败绩',
    zone: 'office',
    quote: '"我追求的，是完美的胜利"',
    stats: {
      '职业': '竞对公司高管',
      '胜率': '无败绩',
      '武器': '国际象棋',
      '外号': '不择手段的检察官',
    },
    phrases: [
      '证人，姓名和职业。',
      '异议！',
      '法庭上，证据就是一切。',
      '看来你已经束手无策了。',
      '对方不过是在虚张声势。',
    ],
  },
  {
    slug: 'itonokogiri',
    img: 'chars/itonokogiri.png',
    facingRight: false,
    name: '糸锯',
    title: '很穷……',
    zone: 'office',
    quote: '"交给我吧，我很擅长对泄露商业机密！"',
    stats: {
      '职业': '某人的下属',
      '搭档': '御剑',
      '特长': '现场调查',
      '性格': '热血',
    },
    phrases: [
      '交给我！',
      '现场已封锁！',
      '有新线索！',
      '这个人就是嫌疑人！',
      '不，不要……我只有500元了……',
    ],
  },
  {
    slug: 'lawyer2',
    img: 'chars/lawyer2.png',
    facingRight: true,
    name: '不知名大叔（？）',
    title: '洗手间主理人',
    zone: 'office',
    quote: '"那么，判决是……"',
    stats: {
      '职业': '洗手间扫地僧',
      '身份': '似乎是一对兄弟？',
      '特征': '秃头',
      '健康水平': '疑似健忘',
    },
    phrases: [
      '......',
      '看来我必须给你一些惩罚。',
      '扰乱秩序！保安！',
      '档案已销毁。',
      '我从未存在过。',
    ],
  },
  {
    slug: 'yahari',
    img: 'chars/yahari.png',
    facingRight: false,
    name: '矢张',
    title: '可疑的家伙',
    zone: 'kitchen',
    quote: '"xx子她啊，真的非常可爱……"',
    stats: {
      '职业': '漫画家',
      '友人': '成步堂&御剑',
      '特长': '恋爱脑',
      '实际身份': '幕后黑手（？）',
    },
    phrases: [
      '我不是可疑人员啊！',
      '你在对本世纪最恩爱的情侣说什么啊！',
      '小冥的鞭鞭大冒险！',
      '……都说了，我真的只是碰巧出现在那里！',
      '我发誓，我发誓啦！真的是亲眼看到的！',
    ],
  },
  {
    slug: 'pink_lady',
    img: 'chars/pink_lady.png',
    facingRight: false,
    name: '粉色小姐',
    title: '似乎只是秘书',
    zone: 'kitchen',
    quote: '"嗯哼～"',
    stats: {
      '职业': '大概是秘书',
      '特征': '粉色❤',
      '身材': '非常好',
      '危险度': '❤❤❤❤❤',
    },
    phrases: [
      '嗯哼～',
      '你在看我吗？',
      '有什么事吗？',
      '我只是路过❤',
      '不告诉你～',
    ],
  },
  {
    slug: 'ooba',
    img: 'chars/ooba.png',
    facingRight: false,
    name: '大场香',
    title: '前台',
    zone: 'kitchen',
    quote: '"咔哒咔哒咔哒咔哒"',
    stats: {
      '职业': '什么都能做！',
      '风格': '强硬',
      '特长': '重力连发',
      '推': '御剑',
    },
    phrases: [
      '咪酱~',
      '大婶我啊年轻时候也是（以下省略500字）',
      '不能让你们进去！',
      '你们这些家伙啊现在的年轻人真的是（以下省略500字）',
      '怎么了现在看到我在这里很惊讶吗大婶我啊（以下省略500字）',
    ],
  },
  {
    slug: 'bentou',
    img: 'chars/bentou.png',
    facingRight: false,
    name: '要买盒饭吗',
    title: '神秘小贩',
    zone: 'kitchen',
    quote: '"要买盒饭吗？"',
    stats: {
      '职业': '大概是小贩',
      '商品': '盒饭',
      '出没地': '地下车库',
      '神秘度': '★★★★★',
    },
    phrases: [
      '要买盒饭吗？',
      '今天的特价！',
      '新鲜出炉！',
      '买一送一！',
      '要尝尝我的特制盒饭吗？',
    ],
  },
  {
    slug: 'shogun',
    img: 'chars/shogun.png',
    facingRight: false,
    name: '将军超人',
    title: '其实是皮套',
    zone: 'toilet',
    quote: '"大江户战士·将军超人"',
    stats: {
      '类型': '机器人',
      '能力': '超强',
      '必杀技': '五月雨突刺',
      '武器': '长枪',
    },
    phrases: [
      '（激昂的音乐声）',
      '（激烈的战斗声）',
      '认输吧！贪官魔人！',
      '必杀技！五月雨突刺！',
      '啊，我的枪……',
    ],
  },
  {
    slug: 'houtsuki',
    img: 'chars/houtsuki.png',
    facingRight: false,
    name: '宝月巴',
    title: '竞对公司CEO',
    zone: 'toilet',
    quote: '"抱歉，我不能说。"',
    stats: {
      '职业': 'CEO',
      '搭档': '？？？',
      '性格': '冷酷（？）',
      '无论如何也要保护的人': '茜',
    },
    phrases: [
      '抱歉，我不能回答这个问题。',
      '小茜……',
    ],
  },
  {
    slug: 'sayuri',
    img: 'chars/sayuri.png',
    facingRight: false,
    name: '小百合',
    title: '工位宠物',
    zone: 'toilet',
    quote: '"小百合，小百合~"',
    stats: {
      '物种': '鹦鹉',
      '特征': '记性很好',
      '主人': '？？？',
      '年龄': '15+',
    },
    phrases: [
      '小百合，小百合~',
      '不可忘记DL-6号事件。',
    ],
  },
  {
    slug: 'cowboy',
    img: 'chars/cowboy.png',
    facingRight: false,
    name: '牛仔（？）',
    title: '？？？',
    zone: 'toilet',
    quote: '"......"',
    stats: {
      '职业': '大概是保安',
      '特征': '牛仔帽',
      '原工作': '刑警',
      '爱好': '刮胡子',
    },
    phrases: [
      '......',
      '（无视）',
    ],
  },
  {
    slug: 'mystery',
    img: 'chars/mystery.png',
    facingRight: false,
    name: '逮捕君',
    title: '公司吉祥物',
    zone: 'toilet',
    quote: '"（欢快的音乐）"',
    stats: {
      '形态': '立牌',
      '行为': '摇晃',
      '目的': '未知',
      '危险度': '极高',
    },
    phrases: [
      '......',
      '（摇晃）',
      '（继续摇晃）',
      '（播放音乐）',
      '（旋转）',
    ],
  },
  {
    slug: 'guard',
    img: 'chars/guard.png',
    facingRight: false,
    name: '保安',
    title: '大概快要被开除了',
    zone: 'toilet',
    quote: '"是！由我来说明"',
    stats: {
      '职业': '保安',
      '职责': '不要弄丢东西',
      '性格': '过分元气',
      '危机': '即将被解雇',
    },
    phrases: [
      '请出示证件！',
      '是！',
      '那个，好像被我弄丢了！',
      '现在是一名保安，是也！',
    ],
  },
];

// ===== 默认显示的角色（slug列表）=====
// 修改这里来改变页面初始显示哪些角色
const defaultVisible = ['naruhodou', 'mayoi'];
