// ============================================================
//  characters.js — 角色数据配置
//  想修改角色介绍、台词、属性，只需编辑这个文件
// ============================================================

const characters = [
  {
    slug: 'naruhodou',
    img: 'chars/naruhodou.png',
    name: '成步堂龙一',
    title: '辩护律师 · 成步堂律师事务所',
    zone: 'office',           // 初始区域：office / kitchen / toilet
    quote: '"逆转！"',         // 角色一句话介绍
    stats: {                  // 点击角色后弹出的属性面板
      '职业': '辩护律师',
      '胜率': '100%',
      '口头禅': '逆转！',
      '发型': '刺猬头',
    },
    phrases: [                // 角色随机说的台词
      '逆转！',
      '异议！',
      '这里有矛盾！',
      '我绝对不会放弃！',
      '真相只有一个！',
    ],
  },
  {
    slug: 'mayoi',
    img: 'chars/mayoi.png',
    name: '真宵',
    title: '灵媒见习生 · 神绪家',
    zone: 'office',
    quote: '"我用灵媒术帮你！"',
    stats: {
      '职业': '灵媒见习生',
      '特技': '灵媒术',
      '最爱': '钢铁侠',
      '食量': '超大',
    },
    phrases: [
      '我饿了...',
      '用灵媒术解决！',
      '姐姐教过我！',
      '钢铁侠最帅！',
      '我来帮你！',
    ],
  },
  {
    slug: 'chihiro',
    img: 'chars/chihiro.png',
    name: '千寻',
    title: '首席律师 · 神绪法律事务所',
    zone: 'office',
    quote: '"证据会说话。"',
    stats: {
      '职业': '首席律师',
      '经验': '丰富',
      '特长': '证据分析',
      '气场': '强大',
    },
    phrases: [
      '证据会说话。',
      '冷静分析。',
      '这个证据很关键。',
      '不要慌张。',
      '真相终会大白。',
    ],
  },
  {
    slug: 'mitsurugi',
    img: 'chars/mitsurugi.png',
    name: '御剑怜侍',
    title: '检察官 · 无败绩',
    zone: 'office',
    quote: '"我从未输过。"',
    stats: {
      '职业': '检察官',
      '胜率': '无败绩',
      '武器': '钢笔',
      '外号': '冰之检察官',
    },
    phrases: [
      '我从未输过。',
      '异议！',
      '无关紧要。',
      '证明给我看。',
      '这不过是小事。',
    ],
  },
  {
    slug: 'itonokogiri',
    img: 'chars/itonokogiri.png',
    name: '糸锯圭介',
    title: '刑警 · 警视厅',
    zone: 'office',
    quote: '"交给我！"',
    stats: {
      '职业': '刑警',
      '搭档': '成步堂',
      '特长': '现场调查',
      '性格': '热血',
    },
    phrases: [
      '交给我！',
      '现场已封锁！',
      '有新线索！',
      '嫌疑人锁定！',
      '我来调查！',
    ],
  },
  {
    slug: 'lawyer2',
    img: 'chars/lawyer2.png',
    name: '法务（？）',
    title: '神秘律师 · 身份不明',
    zone: 'office',
    quote: '"......"',
    stats: {
      '职业': '律师？',
      '身份': '不明',
      '档案': '机密',
      '危险度': '★★★★★',
    },
    phrases: [
      '......',
      '不需要解释。',
      '你不需要知道。',
      '档案已销毁。',
      '我从未存在过。',
    ],
  },
  {
    slug: 'yahari',
    img: 'chars/yahari.png',
    name: '矢张政志',
    title: '刑警 · 警视厅',
    zone: 'kitchen',
    quote: '"我是警察！"',
    stats: {
      '职业': '刑警',
      '搭档': '糸锯',
      '特长': '体力充沛',
      '口头禅': '我是警察！',
    },
    phrases: [
      '我是警察！',
      '停下！',
      '有情况！',
      '嫌疑人跑了！',
      '增援请求！',
    ],
  },
  {
    slug: 'pink_lady',
    img: 'chars/pink_lady.png',
    name: '粉色小姐',
    title: '神秘人物 · 身份不明',
    zone: 'kitchen',
    quote: '"嗯哼～"',
    stats: {
      '职业': '???',
      '特征': '粉色系',
      '性格': '神秘',
      '危险度': '未知',
    },
    phrases: [
      '嗯哼～',
      '你在看我吗？',
      '有什么事吗？',
      '我只是路过。',
      '不告诉你～',
    ],
  },
  {
    slug: 'ooba',
    img: 'chars/ooba.png',
    name: '大场香',
    title: '检察官 · 精英',
    zone: 'kitchen',
    quote: '"证据确凿。"',
    stats: {
      '职业': '检察官',
      '风格': '强硬',
      '特长': '逻辑推理',
      '胜率': '极高',
    },
    phrases: [
      '证据确凿。',
      '异议！',
      '逻辑不通。',
      '你的辩护无效。',
      '认罪吧。',
    ],
  },
  {
    slug: 'bentou',
    img: 'chars/bentou.png',
    name: '要买盒饭吗',
    title: '神秘小贩 · 法庭常客',
    zone: 'kitchen',
    quote: '"要买盒饭吗？"',
    stats: {
      '职业': '小贩',
      '商品': '盒饭',
      '出没地': '法庭走廊',
      '神秘度': '★★★★★',
    },
    phrases: [
      '要买盒饭吗？',
      '今天的特价！',
      '新鲜出炉！',
      '买一送一！',
      '盒饭盒饭～',
    ],
  },
  {
    slug: 'shogun',
    img: 'chars/shogun.png',
    name: '将军超人',
    title: '机器人 · 型号不明',
    zone: 'toilet',
    quote: '"我是将军超人！"',
    stats: {
      '类型': '机器人',
      '能力': '超强',
      '弱点': '未知',
      '来历': '神秘',
    },
    phrases: [
      '我是将军超人！',
      '正义必胜！',
      '系统运行正常。',
      '检测到异常！',
      '执行任务中。',
    ],
  },
  {
    slug: 'houtsuki',
    img: 'chars/houtsuki.png',
    name: '宝月巴',
    title: '侦探 · 独立调查员',
    zone: 'toilet',
    quote: '"线索就在眼前。"',
    stats: {
      '职业': '侦探',
      '特长': '调查',
      '性格': '认真',
      '直觉': '敏锐',
    },
    phrases: [
      '线索就在眼前。',
      '这里有问题。',
      '继续调查。',
      '真相快出来了。',
      '不放过任何细节。',
    ],
  },
  {
    slug: 'sayuri',
    img: 'chars/sayuri.png',
    name: '小百合',
    title: '法庭助理 · 检察厅',
    zone: 'toilet',
    quote: '"请问有什么需要帮忙的吗？"',
    stats: {
      '职业': '法庭助理',
      '性格': '温柔',
      '特长': '文书整理',
      '人缘': '极好',
    },
    phrases: [
      '请问需要帮忙吗？',
      '文件整理好了。',
      '请签收这份文件。',
      '今天也要加油！',
      '有什么我能做的？',
    ],
  },
  {
    slug: 'cowboy',
    img: 'chars/cowboy.png',
    name: '牛仔（？）',
    title: '神秘人 · 来历不明',
    zone: 'toilet',
    quote: '"......"',
    stats: {
      '职业': '???',
      '特征': '牛仔帽',
      '来历': '不明',
      '危险度': '未知',
    },
    phrases: [
      '......',
      '你好。',
      '我只是路过。',
      '别问我。',
      '再见。',
    ],
  },
  {
    slug: 'mystery',
    img: 'chars/mystery.png',
    name: '神秘摇晃立牌',
    title: '??? · 存在本身是谜',
    zone: 'toilet',
    quote: '"......"',
    stats: {
      '形态': '立牌',
      '行为': '摇晃',
      '目的': '未知',
      '危险度': '极高',
    },
    phrases: [
      '......',
      '（摇晃）',
      '（继续摇晃）',
      '（剧烈摇晃）',
      '......',
    ],
  },
  {
    slug: 'guard',
    img: 'chars/guard.png',
    name: '保安',
    title: '守卫 · 法庭大楼',
    zone: 'toilet',
    quote: '"请出示证件。"',
    stats: {
      '职业': '保安',
      '职责': '维持秩序',
      '性格': '严肃',
      '工龄': '10年',
    },
    phrases: [
      '请出示证件。',
      '禁止入内！',
      '保持安静。',
      '请走正门。',
      '例行检查。',
    ],
  },
];

// ===== 默认显示的角色（slug列表）=====
// 修改这里来改变页面初始显示哪些角色
const defaultVisible = ['naruhodou', 'mayoi'];
